# This workflow runs when new change is pushed to repo OR when a new PR is created
# It performs all of the tests to make sure everything is good.

---
name: PR Runner

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn ci:lint

      - name: Typecheck
        run: yarn ci:typecheck

      - name: Build
        run: yarn ci:build

      - name: Run tests
        run: yarn ci:test
